using Avalonia.Controls;
using Avalonia.Platform;

namespace RepoWatch.Desktop.Platform;

/// <summary>
/// Loads the packaged app/tray icon (Assets/RepoWatch.ico, regenerated by scripts/make-icon.ps1). The same file is
/// the executable's ApplicationIcon, so Explorer, the taskbar, the tray and notifications all show one mark.
/// </summary>
public static class AppIconFactory
{
    public static readonly Uri IconUri = new("avares://RepoWatch/Assets/RepoWatch.ico");

    public static WindowIcon Create()
    {
        using var stream = AssetLoader.Open(IconUri);
        return new WindowIcon(stream);
    }
}
